# Generated by Django 5.0.1 on 2024-01-13 09:36

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('slot', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^01\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='EBooklet',
            fields=[
                ('booklet_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^B\\d{7}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('complaints', models.TextField()),
                ('diagnosis', models.TextField()),
                ('rx', models.TextField()),
                ('investigation', models.TextField()),
                ('lifestyle', models.TextField()),
                ('last_checkup_id', models.IntegerField(blank=True, default=0)),
                ('pulse_rate', models.IntegerField()),
                ('bp', models.CharField(max_length=6)),
                ('temp', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('roster_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^01\\d{9}$')])),
                ('permanent_address', models.TextField()),
                ('gender', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[MF]$')])),
                ('hall_name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('blood_group', models.CharField(max_length=3)),
                ('transaction_id', models.CharField(max_length=10, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('department', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^01\\d{9}$')])),
                ('permanent_address', models.TextField()),
                ('hall_name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('blood_group', models.CharField(max_length=3)),
                ('transaction_id', models.CharField(max_length=10, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='dayslot',
            constraint=models.UniqueConstraint(fields=('day', 'slot'), name='unique_day_slot'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='booklet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuetMedicalApp.ebooklet'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuetMedicalApp.doctor'),
        ),
        migrations.AddField(
            model_name='roster',
            name='dayslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuetMedicalApp.dayslot'),
        ),
        migrations.AddField(
            model_name='roster',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuetMedicalApp.doctor'),
        ),
        migrations.AddField(
            model_name='ebooklet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CuetMedicalApp.student'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('dayslot', 'month', 'year'), name='unique_roster_slot_month_year'),
        ),
    ]
