# Generated by Django 5.0.1 on 2024-01-13 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuetMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[MF]$')]),
        ),
    ]
