# Generated by Django 5.0.1 on 2024-01-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuetMedicalApp', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooklet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15),
        ),
    ]
